<div class="postbox closed">
    <div class="handlediv" title="<?php _e('Click to toggle', 'custom-field-template'); ?>"><br /></div>
    <h3><?php _e('Export Options', 'custom-field-template'); ?></h3>
    <div class="inside">
        <form method="post">
            <table class="form-table" style="margin-bottom:5px;">
                <tbody>
                <tr><td>
                        <p><input type="submit" name="custom_field_template_export_options_submit" value="<?php _e('Export Options &raquo;', 'custom-field-template'); ?>" class="button-primary" /></p>
                    </td></tr>
                </tbody>
            </table>
        </form>
    </div>
</div>