<style type="text/css">
    div.grippie {
        background:#EEEEEE url(<?php echo $this->plugin_dir . '/js/'; ?>grippie.png) no-repeat scroll center 2px;
        border-color:#DDDDDD;
        border-style:solid;
        border-width:0pt 1px 1px;
        cursor:s-resize;
        height:9px;
        overflow:hidden;
    }
    .resizable-textarea textarea {
        display:block;
        margin-bottom:0pt;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('textarea.resizable:not(.processed)').TextAreaResizer();
    });
</script>

<?php
/*$viewmodel = new customFieldTemplateModel();
$options = $viewmodel->get_custom_field_template_data();*/
if ( !empty($message) ) : ?>
    <div id="message" class="updated"><p><?php echo $message; ?></p></div>
<?php endif; ?>
<?php if ( !empty($errormessage) ) : ?>
    <div id="errormessage" class="error"><p><?php echo $errormessage; ?></p></div>
<?php endif; ?>
<div class="wrap">
    <div id="icon-plugins" class="icon32"><br/></div>
    <h2><?php _e('Custom Field Template', 'custom-field-template'); ?></h2>

    <br class="clear"/>

    <div id="poststuff" style="position: relative; margin-top:10px;">
        <?php if ( empty($options['custom_field_template_disable_ad']) ) {
            echo '<div style="width:75%; float:left;">';
        }


        foreach ($submitButtonArray as $setableOption) {
                require_once($setableOption.'.phtml');
        } ;?>
        </div>

        <?php if ( empty($options['custom_field_template_disable_ad']) ) : ?>
            <div style="width:24%; float:right;">
                <div class="postbox" style="min-width:200px;">
                    <div class="handlediv" title="<?php _e('Click to toggle', 'custom-field-template'); ?>"><br /></div>
                    <h3><?php _e('Donation', 'custom-field-template'); ?></h3>
                    <div class="inside">
                        <p><?php _e('If you liked this plugin, please make a donation via paypal! Any amount is welcome. Your support is much appreciated.', 'custom-field-template'); ?></p>
                        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                            <input type="hidden" name="cmd" value="_s-xclick">
                            <input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----
                            MIIHRwYJKoZIhvcNAQcEoIIHODCCBzQCAQExggEwMIIBLAIBADCBlD
                            CBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQ
                            HEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5j
                            LjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2Z
                            V9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQ
                            AwDQYJKoZIhvcNAQEBBQAEgYBtdqV+6h22z5VEGpppRcda++0
                            DSLWRP//kuiOr2S+WQO9mIBkiZB/z+0EhPo12BU6m3+axks0o
                            OfByqUwTWtOx/tj2eKmf3nCEb6WOej0Xbas0p997aTtCZL6nI
                            2kH09lVW9+TTm+/9fss827Trv/EUwgbRXvBXDojcTIoxDxRqD
                            ELMAkGBSsOAwIaBQAwgcQGCSqGSIb3DQEHATAUBggqhkiG9w0
                            DBwQInYRI4v1U77SAgaDVlmZwGSL8qAoj5biTKEelYlHFm3tV
                            JkJiRigaY+RMt16iT8fFj4NdlCRvCQiaAGVI+YLAIFsImxWMo
                            2pYH7hrC9B5nYPLnYGd5hVF7o8srFPVB65fSXukjRJ/WHkirH
                            QLw6uLijir+etkdr7vOmmOVcQRFwqYCeqwT75OLelaIUcoDcR
                            cLTWtjy/bWdAxAKg/RF08HsVgD7WapuBQqP5XoIIDhzCCA4Mw
                            ggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVB
                            AYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW
                            4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAs
                            UCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJ
                            KoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwM
                            TMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQ
                            swCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzE
                            UMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVf
                            Y2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNA
                            QkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4
                            GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPu
                            msJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88p
                            b5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3Nmoh
                            qM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMI
                            HrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwY
                            DVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSB
                            kTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDV
                            QQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW
                            5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl
                            2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22C
                            AQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBX
                            zpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+I
                            obhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/Xq
                            Xa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvr
                            uKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswC
                            QYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW
                            50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQY
                            DVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEc
                            MBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrD
                            gMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBg
                            kqhkiG9w0BCQUxDxcNMTUwNzIyMjAxMzQ0WjAjBgkqhkiG9w0
                            BCQQxFgQUEKRDIIfM2ADKkxZut/aZdG1rzjwwDQYJKoZIhvcN
                            AQEBBQAEgYANonpXtXN+2MULooVlrBiGOTbhOw3oDsfFV77DE
                            qkSBYFPMVu1pZeHk5MInv8MegRuVXPZuxolitflqvohgQQ8pB
                            njeCcZdUKaYwgrYa9Heda7M5itlGmR0MMy/VbksqE0bJTAB+D
                            OMJFPe+EgH1QrDCJIF+D+5E1elc6Lf/67lg==-----END PKCS7-----">
                            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
                        </form>

                    </div>
                </div>
            </div>
        <?php endif; ?>

        <script type="text/javascript">
            // <![CDATA[
            <?php if ( version_compare( substr($wp_version, 0, 3), '2.7', '<' ) ) { ?>
            jQuery('.postbox h3').prepend('<a class="togbox">+</a> ');
            <?php } ?>
            jQuery('.postbox div.handlediv').click( function() { jQuery(jQuery(this).parent().get(0)).toggleClass('closed'); } );
            jQuery('.postbox h3').click( function() { jQuery(jQuery(this).parent().get(0)).toggleClass('closed'); } );
            jQuery('.postbox.close-me').each(function(){
                jQuery(this).addClass("closed");
            });
            //-->
        </script>

    </div>