<div class="postbox closed">
    <div class="handlediv" title="<?php _e('Click to toggle', 'custom-field-template'); ?>"><br /></div>
    <h3><?php _e('Option List', 'custom-field-template'); ?></h3>
    <div class="inside">
        ex.<br />
        [Plan]<br />
        type = textfield<br />
        size = 35<br />
        hideKey = true<br />

        <table class="widefat" style="margin:10px 0 5px 0;">
            <thead>
            <tr>
                <th>type</th><th>text or textfield</th><th>checkbox</th><th>radio</th><th>select</th><th>textarea</th><th>file</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>hideKey</th><td>hideKey = true</td><td>hideKey = true</td><td>hideKey = true</td><td>hideKey = true</td><td>hideKey = true</td><td>hideKey = true</td>
            </tr>
            <tr>
                <th>label</th><td>label = ABC</td><td>label = DEF</td><td>label = GHI</td><td>label = JKL</td><td>label = MNO</td><td>label = PQR</td>
            </tr>
            <tr>
                <th>size</th><td>size = 30</td><td></td><td></td><td></td><td></td><td>size = 30</td>
            </tr>
            <tr>
                <th>value</th><td></td><td>value = apple # orange # banana</td><td>value = apple # orange # banana</td><td>value = apple # orange # banana</td><td></td>
                <td></td>
            </tr>
            <tr>
                <th>valueLabel</th><td></td><td>valueLabel = apples # oranges # bananas</td><td>valueLabel = apples # oranges # bananas</td><td>valueLabel = apples # oranges # bananas</td><td></td>
                <td></td>
            </tr>
            <tr>
                <th>default</th><td>default = orange</td><td>default = orange # banana</td><td>default = orange</td><td>default = orange</td><td>default = orange</td><td></td>
            </tr>
            <tr>
                <th>clearButton</th><td></td><td></td><td>clearButton = true</td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>selectLabel</th><td></td><td></td><td></td><td>selectLabel = Select a fruit</td><td></td><td></td>
            </tr>
            <tr>
                <th>rows</th><td></td><td></td><td></td><td></td><td>rows = 4</td><td></td>
            </tr>
            <tr>
                <th>cols</th><td></td><td></td><td></td><td></td><td>cols = 40</td><td></td>
            </tr>
            <tr>
                <th>wrap</th><td></td><td></td><td></td><td></td><td>wrap = off</td><td></td>
            </tr>
            <tr>
                <th>tinyMCE</th><td></td><td></td><td></td><td></td><td>tinyMCE = true</td><td></td>
            </tr>
            <tr>
                <th>htmlEditor</th><td></td><td></td><td></td><td></td><td>htmlEditor = true</td><td></td>
            </tr>
            <tr>
                <th>date</th><td>date = true</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>dateFirstDayOfWeek</th><td>dateFirstDayOfWeek = 0</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>dateFormat</th><td>dateFormat = yyyy/mm/dd</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>startDate</th><td>startDate = '1970/01/01'</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>endDate</th><td>endDate = (new Date()).asString()</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>readOnly</th><td>readOnly = true</td><td></td><td></td><td></td><td></td><td></td>
            </tr>
            <tr>
                <th>mediaButton</th><td></td><td></td><td></td><td></td><td>mediaButton = true</td><td></td>
            </tr>
            <tr>
                <th>mediaOffImage</th><td></td><td></td><td></td><td></td><td>mediaOffImage = true</td><td></td>
            </tr>
            <tr>
                <th>mediaOffVideo</th><td></td><td></td><td></td><td></td><td>mediaOffVideo = true</td><td></td>
            </tr>
            <tr>
                <th>mediaOffAudio</th><td></td><td></td><td></td><td></td><td>mediaOffAudio = true</td><td></td>
            </tr>
            <tr>
                <th>mediaOffMedia</th><td></td><td></td><td></td><td></td><td>mediaOffMedia = true</td><td></td>
            </tr>
            <tr>
                <th>relation</th><td></td><td></td><td></td><td></td><td></td><td>relation = true</td>
            </tr>
            <tr>
                <th>mediaLibrary</th><td></td><td></td><td></td><td></td><td></td><td>mediaLibrary = true</td>
            </tr>
            <tr>
                <th>mediaPicker</th><td></td><td></td><td></td><td></td><td></td><td>mediaPicker = true</td>
            </tr>
            <tr>
                <th>mediaRemove</th><td></td><td></td><td></td><td></td><td></td><td>mediaRemove = true</td>
            </tr>
            <tr>
                <th>code</th><td>code = 0</td><td>code = 0</td><td>code = 0</td><td>code = 0</td><td>code = 0</td><td></td>
            </tr>
            <tr>
                <th>editCode</th><td>editCode = 0</td><td>editCode = 0</td><td>editCode = 0</td><td>editCode = 0</td><td>editCode = 0</td><td>editCode = 0</td>
            </tr>
            <tr>
                <th>level</th><td>level = 1</td><td>level = 3</td><td>level = 5</td><td>level = 7</td><td>level = 9</td><td>level = 10</td>
            </tr>
            <tr>
                <th>insertTag</th><td>insertTag = true</td><td>insertTag = true</td><td>insertTag = true</td><td>insertTag = true</td><td>insertTag = true</td><td></td>
            </tr>
            <tr>
                <th>tagName</th><td>tagName = movie_tag</td><td>tagName = book_tag</td><td>tagName = img_tag</td><td>tagName = dvd_tag</td><td>tagName = bd_tag</td><td></td>
            </tr>
            <tr>
                <th>output</th><td>output = true</td><td>output = true</td><td>output = true</td><td>output = true</td><td>output = true</td><td></td>
            </tr>
            <tr>
                <th>outputCode</th><td>outputCode = 0</td><td>outputCode = 0</td><td>outputCode = 0</td><td>outputCode = 0</td><td>outputCode = 0</td><td></td>
            </tr>
            <tr>
                <th>outputNone</th><td>outputNone = No Data</td><td>outputNone = No Data</td><td>outputNone = No Data</td><td>outputNone = No Data</td><td>outputNone = No Data</td><td></td>
            </tr>
            <tr>
                <th>singleList</th><td>singleList = true</td><td>singleList = true</td><td>singleList = true</td><td>singleList = true</td><td>singleList = true</td><td></td>
            </tr>
            <tr>
                <th>shortCode</th><td>shortCode = true</td><td>shortCode = true</td><td>shortCode = true</td><td>shortCode = true</td><td>shortCode = true</td><td></td>
            </tr>
            <tr>
                <th>multiple</th><td>multiple = true</td><td></td><td>multiple = true</td><td>multiple = true</td><td>multiple = true</td><td>multiple = true</td>
            </tr>
            <tr>
                <th>startNum</th><td>startNum = 5</td><td></td><td>startNum = 5</td><td>startNum = 5</td><td>startNum = 5</td><td>startNum = 5</td>
            </tr>
            <tr>
                <th>endNum</th><td>endNum = 10</td><td></td><td>endNum = 10</td><td>endNum = 10</td><td>endNum = 10</td><td>endNum = 10</td>
            </tr>
            <tr>
                <th>multipleButton</th><td>multipleButton = true</td><td></td><td>multipleButton = true</td><td>multipleButton = true</td><td>multipleButton = true</td><td>multipleButton = true</td>
            </tr>
            <tr>
                <th>blank</th><td>blank = true</td><td>blank = true</td><td>blank = true</td><td>blank = true</td><td>blank = true</td><td>blank = true</td>
            </tr>
            <tr>
                <th>sort</th><td>sort = asc</td><td>sort = desc</td><td>sort = asc</td><td>sort = desc</td><td>sort = asc</td><td></td>
            </tr>
            <tr>
                <th>search</th><td>search = true</td><td>search = true</td><td>search = true</td><td>search = true</td><td>search = true</td>
            </tr>
            <tr>
                <th>class</th><td>class = text</td><td>class = checkbox</td><td>class = radio</td><td>class = select</td><td>class = textarea</td><td>class = file</td>
            </tr>
            <tr>
                <th>style</th><td>style = color:#FF0000;</td><td>style = color:#FF0000;</td><td>style = color:#FF0000;</td><td>style = color:#FF0000;</td><td>style = color:#FF0000;</td><td>style = color:#FF0000;</td>
            </tr>
            <tr>
                <th>before</th><td>before = abcde</td><td></td><td>before = abcde</td><td>before = abcde</td><td>before = abcde</td><td>before = abcde</td>
            </tr>
            <tr>
                <th>after</th><td>after = abcde</td><td></td><td>after = abcde</td><td>after = abcde</td><td>after = abcde</td><td>after = abcde</td>
            </tr>
            <tr>
                <th>valueCount</th><td>valueCount = true</td><td>valueCount = true</td><td>valueCount = true</td><td>valueCount = true</td><td>valueCount = true</td><td></td>
            </tr>
            <tr>
                <th>JavaScript Event Handlers</th><td>onclick = alert('ok');</td><td>onchange = alert('ok');</td><td>onchange = alert('ok');</td><td>onchange = alert('ok');</td><td>onfocus = alert('ok');</td><td></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>