<div class="postbox closed">
    <div class="handlediv" title="<?php _e('Click to toggle', 'custom-field-template'); ?>"><br /></div>
    <h3><?php _e('Delete Options', 'custom-field-template'); ?></h3>
    <div class="inside">
        <form method="post" onsubmit="return confirm('<?php _e('Are you sure to delete options? Options you set will be deleted.', 'custom-field-template'); ?>');">
            <table class="form-table" style="margin-bottom:5px;">
                <tbody>
                <tr><td>
                        <p><input type="submit" name="custom_field_template_delete_options_submit" value="<?php _e('Delete Options &raquo;', 'custom-field-template'); ?>" class="button-primary" /></p>
                    </td></tr>
                </tbody>
            </table>
        </form>
    </div>
</div>